version: '3.8'

services:
  proxy:
    # image: nihad906/jap-week2-nihad-proxy:latest
    build: 
      context: ./
    ports:
      - "8000:80"    
      - "8443:443"   
    volumes:
      - ./certs:/etc/ssl/certs 
    networks:
      - web_network
  
networks:
  web_network:
    external: true
