version: '3.8'

services:
  web1:
    # image: nihad906/jap-week2-nihad-web1:latest
    build: 
      context: ./
    container_name: web2
    ports:
      - "9090:9090"
    expose:
      - "9090"   
    networks:
      - web_network

networks:
  web_network:
    external: true